### ISSUE TITLE
S3 storage for AWS Lambda code files

### ISSUE THREAD

**Issue by hi4rahul** [iann0036/former2#133]
Hi Ian,

I used the tool today and loved it. It's brilliant, slick, neat and very helpful! 

Can you help me get an insight on how does the storage mechanism work for AWS Lambda code on s3. I noticed on the generated Cloud Formation etc, that the code is referenced from an S3 bucket and has a account specific folder structure, but am looking to understand that how is it managed there? I will really appreciate your thought on the specifics here.

Also, are you considering mechanisms where this code could be stored on the requesters s3 bucket?

Thanks,
Rahul

**Comment by iann0036** [comment]
Hey @hi4rahul,

Thanks for reaching out!

Internally, each AWS customer has a set amount of space within an AWS managed bucket for the purposes of storing Lambda packages. When you deploy your Lambda, you're specifying an S3 location where the Lambda service can obtain a _copy_ of your package for it to duplicate. This unfortunately means Former2 has no concept of where that code originally came from, so uses the location provided (which, I believe, would work in a deployment scenario).

I'll have a look into this further to see if I can trace back the originating bucket, but for now, you'll have to modify your template accordingly.

**Comment by typex1** [comment]
Hi Ian,

as this issue is still open I want to clarify the current state of the Lambda code specification included in the Former2 Cloudformation templates. So for example if I get this from Former2 as part of my Cloudformation template:
...
    LambdaFunction:
        Type: "AWS::Lambda::Function"
        Properties:
            Description: ""
            FunctionName: "my-Lambda-function"
            Handler: "lambda_function.lambda_handler"
            Code:
                S3Bucket: "prod-04-2014-tasks"
                S3Key: !Sub "/snapshots/${AWS::AccountId}/my-Lambda-function-0c7556d9-bbca-4b0b-8dda-cd345ee3a6d2"
                S3ObjectVersion: "oYnh_RN9fdJoiF1dWXRJBhCLNNezBZFu"
            MemorySize: 128
...

then I get "S3 bucket access denied" when trying to execute this template in my account. At first this was not what I expected, but from your statement above the correct way to handle this would be to place the Lambda code in a bucket in my account and adjust the template accordingly, is that correct?

Kind regards
Frank

**Comment by iann0036** [comment]
Hey @typex1,

That's correct. You'd just have to adjust the `Code` block to specify your source location as you deploy it.
