### ISSUE TITLE
Support for Terraform Output of SSO Permission Sets

### ISSUE THREAD

**Issue by marcelinho09** [iann0036/former2#291]
I'd love to have the output of the SSO Permission Sets for Terraform. CloudFormation, CDK etc. is working fine, just Terraform is missing at the moment.

**Comment by iann0036** [comment]
Hey @marcelinho09,

Thanks for raising! I've added the mapping for the SSO Permission Sets for Terraform for you, including the inline policy and managed policy attachments. Let me know how that goes.

Note that not all types have Terraform coverage at this time simply due to the effort / backlog required.

**Comment by marcelinho09** [comment]
Hi @iann0036 ! Thanks alot for this immediate implementation. Really appreciate that, works like a charm. :)
