### ISSUE TITLE
Trying to generate S3 Buckets hangs browser(Chrome and Edge Chrome)

### ISSUE THREAD

**Issue by schwinbp** [iann0036/former2#75]
This has been going on for a several weeks now. I am able to scan the account but as soon as I try to "Add Selected" particularly for a selected S3 bucket or Ec2 Instance the browser just hangs. I have tried this in Google Chrome and Edge Chrome each with the extension installed. 
![image](https://user-images.githubusercontent.com/7315782/80022364-f56b2280-84a9-11ea-9bbe-4f96a1d94e1e.png)
ut the extension()

**Comment by schwinbp** [comment]
Just some more info here... I installed the CLI version, ran it and it worked without issue. So proceeding with that. 
BTW... I was able to recreate the issue on my work and home pc. I thought maybe some enterprise "security" may have been the issue, but my home PC did the exact same thing.

**Comment by iann0036** [comment]
Hey @schwinbp,

Thanks for raising and sorry you ran into issues.

I found your issue fairly easily with your replication steps (I was running with a setting that made me not notice the issue). It was an issue due to computational complexity of generating logical IDs for potential related resources when using sequential logical IDs (the default setting).

I've pushed a fix that hopefully should solve the issue fully, but let me know if they still occur.

Thanks again!

**Comment by schwinbp** [comment]
Thank you!!! I didn't realize how reliant I am on this tool until I was unable to use it. I typically work in Terraform but occasionally have to do some CF for Landing Zone changes, so it is my goto for RevEng-ing stuff into CF. Such a great tool you have created here! Thanks for all your effort!

**Comment by iann0036** [comment]
Thanks for confirming @schwinbp,

Let me know if there are Terraform services you'd like prioritised for coverage.
